-- CivicCam Supabase Schema
-- Run this in the Supabase SQL Editor (https://supabase.com/dashboard/project/rdythbwtcmgmhldzfzem/sql)

-- 1. Create incidents table
CREATE TABLE IF NOT EXISTS incidents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    license_plate TEXT,
    plate_confidence REAL,
    location TEXT,
    source TEXT,
    frame_url TEXT,
    plate_image_url TEXT,
    waste_image_url TEXT,
    video_clip_url TEXT,
    detections JSONB,
    status TEXT DEFAULT 'pending',
    notes TEXT,
    alert_sent BOOLEAN DEFAULT FALSE
);

-- 2. Enable Row Level Security
ALTER TABLE incidents ENABLE ROW LEVEL SECURITY;

-- 3. RLS Policies - Allow full access via anon key (simple setup)
DROP POLICY IF EXISTS "Allow public read" ON incidents;
CREATE POLICY "Allow public read" ON incidents
    FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public insert" ON incidents;
CREATE POLICY "Allow public insert" ON incidents
    FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public update" ON incidents;
CREATE POLICY "Allow public update" ON incidents
    FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Allow public delete" ON incidents;
CREATE POLICY "Allow public delete" ON incidents
    FOR DELETE USING (true);

-- 4. Create the Storage bucket for incident images
INSERT INTO storage.buckets (id, name, public)
VALUES ('incident-images', 'incident-images', true)
ON CONFLICT (id) DO NOTHING;

-- 5. Storage Policies
-- Allow public read access to incident images
DROP POLICY IF EXISTS "Public Read Access" ON storage.objects;
CREATE POLICY "Public Read Access"
    ON storage.objects FOR SELECT
    USING (bucket_id = 'incident-images');

-- Allow uploads to incident images bucket
DROP POLICY IF EXISTS "Allow Uploads" ON storage.objects;
CREATE POLICY "Allow Uploads"
    ON storage.objects FOR INSERT
    WITH CHECK (bucket_id = 'incident-images');

-- Allow updates (overwrite)
DROP POLICY IF EXISTS "Allow Updates" ON storage.objects;
CREATE POLICY "Allow Updates"
    ON storage.objects FOR UPDATE
    USING (bucket_id = 'incident-images');

-- 6. Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_incidents_timestamp ON incidents(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_incidents_status ON incidents(status);
CREATE INDEX IF NOT EXISTS idx_incidents_plate ON incidents(license_plate);
